services:
  nvr:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 5001:5001
    volumes:
      - ./data:/data
      - /mnt/data:/mnt/data
    env_file:
      - .env
    environment:
      - TZ=America/New_York
      - FLASK_PORT=5001
      - RETENTION_DAYS=${RETENTION_DAYS:-7}
      - RECORDINGS_PATH=/mnt/data
    restart: always
    container_name: nvr_app

  restart-service:
    image: alpine:latest
    depends_on:
      - nvr
    command: |
      sh -c '
      apk add --no-cache inotify-tools &&
      sleep 5 &&
      echo "Setting up restart file watcher..." &&
      echo "0 4 * * * kill -1 1" | tee /etc/crontabs/root &&
      echo "Cron job set up. Starting file watcher..." &&
      while true; do
        if [ -f /tmp/restart_nvr ]; then
          echo "Restart signal detected!"
          rm -f /tmp/restart_nvr
          kill -1 1
          sleep 5
        fi
        sleep 2
      done'
    volumes:
      - /tmp:/tmp
    environment:
      - TZ=America/New_York
    restart: always